linters:
  ImportantRule:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 4
  SelectorDepth:
    enabled: true
    max_depth: 4
  QualifyingElement:
    enabled: false
  VendorPrefix:
    enabled: false
