version: 2
jobs:
  docs_sphinx_book_theme:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user .[themes]

      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            export HTML_THEME=sphinx_book_theme
            sphinx-build -W -b html docs docs/_build/html
      - store_artifacts:
          path: docs/_build/html/
          destination: html


workflows:
  version: 2
  default:
    jobs:
      - docs_sphinx_book_theme
